Refactor the UI with Win11 style
DinoChan/Loaf pull request #24
Opened 2021-12-20 12:20 UTC by Richasy

**做了什么**

1. 使用 Win11 风格重制 UI.
2. 调整最小应用窗口大小和初始化窗口大小为 612x740.
3. 添加**关于&设置**页面，为以后可能的设置项（比如摸鱼风格）做准备.

**已知问题**

Win10 会出现双重标题栏，因为在 Win10 中，`AppWindow.TitleBar` 始终会返回 `null`.

**截图**

![image](https://user-images.githubusercontent.com/27713596/146765400-97b112a5-040c-4ccb-8f32-779f8aea9207.png)
![image](https://user-images.githubusercontent.com/27713596/146765778-a2a54f21-6cdf-4df7-a672-c4b5aa4b3765.png)
![image](https://user-images.githubusercontent.com/27713596/146765856-ebd4e6e3-73b6-475d-b973-56345dfb99ea.png)
![image](https://user-images.githubusercontent.com/27713596/146765905-fee0fa8a-d3a4-41fc-bb57-679b3a3ccb39.png)

2021-12-20 12:47 UTC, DinoChan commented
感谢云之幻大佬的设计。预计将在Windows App SDK 1.1 发布后合并这个设计。

2021-12-20 12:51 UTC, Richasy commented
> 感谢云之幻大佬的设计。预计将在Windows App SDK 1.1 发布后合并这个设计。

感谢Dino大佬的项目，让我等打工仔有一个非常棒的工具🥳

2022-01-20 15:43 UTC, HEIGE-PCloud requested changes

2022-01-20 15:43 UTC, HEIGE-PCloud commented on Loaf/MainWindow.xaml
> +    <Grid x:Name="Root" Background="{ThemeResource WindowHostBrush}">
在这里设置 `Background` 会使更新界面的背景也显示为 `WindowHostBrush`

<img width="1080" alt="image" src="https://user-images.githubusercontent.com/52968553/150370015-3187ce1f-f0b0-41e9-ae59-5b66510627d6.png">

建议在 Windows11UpdateView.xaml 中给 grid 添加纯黑色背景。

```xml
<Grid Background="Black">
```

或者给那三个 TextBlock 的 Foreground 提供一个单独的 Brush。

2022-09-09 08:08 UTC, merged